ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY .buildx/gitlab-shell/ /home/git/gitlab-shell/
COPY .buildx/gitlab-gitaly/ruby/ /home/git/gitaly/ruby/
COPY .buildx/gitlab-workhorse/ .buildx/gitlab-gitaly/bin/ .buildx/gitlab-pages/ /usr/local/bin/