ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

ENV GITLAB_HOME="/home/git" \
    GITLAB_SHELL_INSTALL_DIR="${GITLAB_HOME}/gitlab-shell" \
    GITLAB_GITALY_INSTALL_DIR="${GITLAB_HOME}/gitaly" \

COPY .buildx/gitlab-shell/ ${GITLAB_SHELL_INSTALL_DIR}/
COPY .buildx/gitlab-workhorse/ /usr/local/bin/
COPY .buildx/gitlab-pages/ /usr/local/bin/
COPY .buildx/gitlab-gitaly/ruby .buildx/gitlab-gitaly/config.toml.example ${GITLAB_GITALY_INSTALL_DIR}/
COPY .buildx/gitlab-gitaly/bin/ /usr/local/bin/
