ARG GIT_IMAGE="registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-git:v14.2.3-amd64"
ARG RAILS_IMAGE="registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-rails:v14.2.3-amd64"
ARG RUBY_IMAGE="registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-ruby:2.7.4-amd64"

FROM ${RAILS_IMAGE} as rails
FROM ${GIT_IMAGE} as builder

FROM ${RUBY_IMAGE}

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=14.1.3

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS=linux
ARG TARGETARCH=amd64

ARG DATADIR=/var/opt/gitlab
ARG CONFIG=/srv/gitlab/config
ARG GITLAB_USER=git

# create gitlab user
RUN adduser --disabled-password --gecos 'GitLab' ${GITLAB_USER} && \
  install -d -o ${GITLAB_USER} /var/log/gitlab/ && \
  install -d -o ${GITLAB_USER} ${DATADIR} && \
  install -d -o ${GITLAB_USER} ${CONFIG}

COPY .buildx/${TARGETOS}/${TARGETARCH}/gitlab-* /usr/local/bin/

COPY --from=builder /usr/bin/git /usr/bin/git-cvsserver /usr/bin/git-shell /usr/bin/

RUN ln -s /usr/bin/git /usr/bin/git-receive-pack && \
ln -s /usr/bin/git /usr/bin/git-upload-archive && \
ln -s /usr/bin/git /usr/bin/git-upload-pack

COPY --from=rails --chown=git /srv/gitlab/public/ /srv/gitlab/public/

COPY --from=rails --chown=git /srv/gitlab/doc/ /srv/gitlab/doc/

USER $GITLAB_USER:$GITLAB_USER

COPY .beagle/gitlab-workhorse/scripts/ /scripts/

CMD /scripts/start-workhorse

HEALTHCHECK --interval=30s --timeout=30s --retries=5 \
CMD /scripts/healthcheck
