ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

USER root
RUN apt-get update &&  apt-get install -y git
RUN rm -r /srv/gitlab/public/assets
ADD ./public/assets /srv/gitlab/public/assets  
USER $GITLAB_USER:$GITLAB_USER
