ARG BASE=registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-ruby:2.7.2-amd64
ARG PG_IMAGE="registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-postgresql:13.2-amd64"
ARG GM_IMAGE="registry.cn-qingdao.aliyuncs.com/wod-arm/gitlab-graphicsmagick:1.3.36-amd64"
FROM ${PG_IMAGE} as pg_image
FROM ${GM_IMAGE} as graphicsmagick_image

FROM $BASE

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    wget ca-certificates apt-transport-https gnupg2 \
 && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

RUN set -ex \
 && wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg  | apt-key add - \
 && echo 'deb https://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list \
 && wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
 && echo 'deb https://deb.nodesource.com/node_14.x focal main' > /etc/apt/sources.list.d/nodesource.list \ 
 && set -ex \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
      nodejs yarn build-essential cmake make gcc g++ \
      libicu-dev libffi-dev libre2-dev musl-dev patch pkg-config libkrb5-3 libc6 \
      git sudo \
 && rm -rf /var/lib/apt/lists/*

# Include postgres dev tools
COPY --from=pg_image /usr/local/psql/bin/ /usr/bin/
COPY --from=pg_image /usr/local/psql/lib/ /usr/lib/
COPY --from=pg_image /usr/local/psql/include/ /usr/include/
COPY --from=pg_image /usr/local/psql/share/ /usr/share/

# Include GraphicsMagick (bin,include,lib,share)
COPY --from=graphicsmagick_image /usr/local/ /usr/local/
